import { createContext, useContext, useState, ReactNode } from "react";

// Define language types
type LanguageType = "en" | "es";

// Dictionary type for translations
interface TranslationDictionary {
  [key: string]: {
    [key: string]: string;
  };
}

// Translations for English and Spanish
const translations: Record<LanguageType, TranslationDictionary> = {
  en: {
    common: {
      search: "Search",
      filter: "Filter",
      home: "Home",
      profile: "Profile",
      settings: "Settings",
      cancel: "Cancel",
      submit: "Submit",
      create: "Create",
      edit: "Edit",
      delete: "Delete",
      save: "Save",
      back: "Back",
      next: "Next",
      continue: "Continue",
      done: "Done",
      welcome: "Welcome",
      loading: "Loading...",
      players: "Players",
      error: "Error",
      notifications: "Notifications"
    },
    auth: {
      signIn: "Sign In",
      signUp: "Sign Up",
      email: "Email",
      password: "Password",
      forgotPassword: "Forgot Password?",
      alreadyHaveAccount: "Already have an account?",
      dontHaveAccount: "Don't have an account?",
      haveAccount: "Already have an account? Sign In",
      createAccount: "Create Account",
      or: "OR",
      continueWithGoogle: "Continue with Google",
      continueWithApple: "Continue with Apple",
      orContinueWith: "Or continue with",
      welcomeBack: "Welcome Back",
      emailSignInDescription: "Enter your email to sign in to your account",
      emailSignUpDescription: "Enter your email to create your account",
      checkEmail: "Check your email",
      confirmationEmailSent: "A confirmation email has been sent"
    },
    home: {
      featuredCourses: "Featured Courses",
      exploreAll: "Explore All",
      nearbyGolfCourses: "Nearby Golf Courses",
      viewAll: "View All",
      upcomingReservations: "Upcoming Reservations",
      noReservations: "You don't have any reservations yet.",
      searchCourses: "Search Courses",
      golfCourses: "Golf Courses",
      noCoursesFound: "No courses found",
      resetFilters: "Reset Filters",
      openNow: "Open Now",
      closed: "Closed",
      openInMap: "Open in Map",
      location: "Location",
      hours: "Hours",
      today: "Today"
    },
    course: {
      holes: "Holes",
      par: "Par",
      openNow: "Open Now",
      closed: "Closed",
      hours: "Hours",
      address: "Address",
      contact: "Contact",
      website: "Website",
      directions: "Get Directions",
      description: "Description",
      reviews: "Reviews",
      photos: "Photos",
      openingHours: "Opening Hours",
      hoursNotAvailable: "Hours not available",
      today: "Today",
      hide: "Hide",
      viewAll: "View All",
      courseStatistics: "Course Statistics",
      noRoundsPlayed: "No rounds played yet",
      totalHoles: "Total Holes",
      totalPar: "Total Par",
      frontNine: "Front Nine",
      backNine: "Back Nine",
      courseTotals: "Course Totals",
      weatherForecast: "Weather Forecast",
      loadingWeather: "Loading weather...",
      tryAgain: "Try Again",
      dayForecast: "5-Day Forecast",
      humidity: "Humidity",
      wind: "Wind",
      courseLocation: "Course Location",
      noRoundsRecorded: "No Rounds Recorded", 
      firstToPlayCourse: "Be the first to play this course and record your score to see statistics and leaderboards!",
      totalRounds: "Total Rounds",
      averageVsPar: "Avg vs Par",
      bestRound: "Best Round",
      players: "Players",
      highestRound: "Highest Round",
      monday: "Monday",
      tuesday: "Tuesday", 
      wednesday: "Wednesday",
      thursday: "Thursday",
      friday: "Friday",
      saturday: "Saturday",
      sunday: "Sunday",
      noReviewsYet: "No reviews yet",
      firstToAddReview: "Be the first to add a review!",
      sunny: "Sunny",
      partlyCloudy: "Partly Cloudy",
      cloudy: "Cloudy",
      overcast: "Overcast",
      rain: "Rain",
      thunderstorm: "Thunderstorm",
      snow: "Snow",
      fog: "Fog",
      haze: "Haze",
      drizzle: "Drizzle",
      mist: "Mist",
      fiveDayForecast: "5-Day Forecast"
    },
    profile: {
      yourProfile: "Your Profile",
      handicap: "Handicap",
      viewStats: "View Stats",
      roundsPlayed: "Rounds Played",
      avgScore: "Average Score",
      bestScore: "Best Score",
      yourRecentRounds: "Your Recent Rounds",
      noRounds: "You haven't recorded any rounds yet.",
      addRound: "Add Round",
      account: "Account",
      holes: "Holes",
      noRoundsRecorded: "No rounds recorded yet",
      addFirstRound: "Add your first round",
      noStatsAvailable: "No statistics available yet",
      startPlayingStats: "Start playing to see your stats!",
      noHandicapYet: "No handicap yet",
      playerStatistics: "Player Statistics",
      recentRounds: "Recent Rounds",
      recordFirstRound: "Record your first round",
      allRounds: "All Rounds",
      viewAllRounds: "View All Rounds",
      viewAll: "View all",
      showLess: "Show Less",
      deleteRound: "Delete Round",
      deleteRoundConfirm: "Are you sure you want to delete this round? This action cannot be undone.",
      score: "Score",
      notes: "Notes",
      underPar: "under par",
      overPar: "over par",
      atPar: "At par",
      logout: "Logout",
      logoutConfirm: "Are you sure you want to log out?",
      logoutSuccess: "Logged out successfully",
      logoutError: "Error logging out",
      totalRounds: "Total Rounds",
      avgVsPar: "Avg vs Par",
      bestRound: "Best Round",
      viewScorecard: "View Scorecard",
      saveChanges: "Save Changes",
      profileUpdateSuccess: "Profile updated successfully",
      profileUpdateError: "Error updating profile",
      fullName: "Full Name",
      username: "Username",
      anonymous: "Anonymous",
      saving: "Saving..."
    },
    filters: {
      showFavorites: "Show Favorites",
      numberOfHoles: "Number of Holes",
      status: "Status",
      favoritesOnly: "Favorites Only",
      currentlyOpen: "Currently Open",
      all: "All",
      topRated: "Top Rated",
      showOnlyFavorites: "Show only your favorite courses",
      showAllCourses: "Show all courses including favorites",
      showOnlyOpen: "Show only open courses",
      showAllStatus: "Show all courses regardless of status",
      findYourCourse: "Find your ideal course"
    },
    addRound: {
      title: "Add Your Round",
      selectCourse: "Select Golf Course",
      chooseCourse: "Choose the golf course where you played your round",
      searchCourse: "Search and select golf course...",
      roundDetails: "Round Details",
      howManyHoles: "How many holes did you play?",
      selected: "Selected",
      enterScores: "Enter Your Scores",
      addScoreHole: "Add your score for each hole",
      addScores: "Add Scores",
      saveRound: "Save Round",
      saving: "Saving...",
      saveSuccess: "Round saved successfully!",
      selectCourseError: "Please select a course",
      loginError: "Please log in to add a round",
      selectGolfCourse: "Select Golf Course",
      chooseCoursePlay: "Choose the course where you want to play",
      searchGolfCourses: "Search golf courses...",
      noGolfCourseFound: "No golf course found.",
      holesPlayed: "Holes Played",
      holes: "Holes",
      select9Holes: "Select 9 Holes",
      choose9Holes: "Choose which 9 holes you played",
      front9: "Front 9",
      back9: "Back 9",
      holes1to9: "Holes 1-9",
      holes10to18: "Holes 10-18",
      step: "Step",
      of: "of"
    },
    rounds: {
      addRound: "Add Round",
      selectCourse: "Select Course",
      date: "Date",
      score: "Score",
      notes: "Notes",
      searchCourses: "Search courses...",
      noCoursesFound: "No courses found",
      courseSearchPlaceholder: "Type to search for a course...",
      roundAdded: "Round added successfully",
      roundAddedDesc: "Your golf round has been saved.",
      courseRequired: "Please select a course",
      scoreRequired: "Please enter your score",
      dateRequired: "Please select a date",
      hole: "Hole",
      par: "Par",
      strokes: "Strokes",
      addShots: "Add Shots",
    },
    reservations: {
      bookTeeTime: "Book Tee Time",
      date: "Date",
      time: "Time",
      players: "Players",
      bookingDetails: "Booking Details",
      confirmBooking: "Confirm Booking",
      bookingConfirmed: "Booking Confirmed",
      bookingFailed: "Booking Failed",
      upcoming: "Upcoming",
      past: "Past",
      cancelReservation: "Cancel Reservation",
      myReservations: "My Reservations",
      noReservations: "No reservations found"
    },
    settings: {
      settings: "Settings",
      legalNotice: "Legal Notice",
      faq: "Frequently Asked Questions",
      language: "Language",
      darkMode: "Dark Mode",
      privacyPolicy: "Privacy Policy",
      termsConditions: "Terms & Conditions"
    },
    legal: {
      effectiveDate: "Effective Date: July 5th, 2025",
      welcomeText: "Welcome to GolfitArgentina, a progressive web application that provides detailed information about all golf courses in Argentina. By accessing or using our App, you agree to be legally bound by these Terms and Conditions. If you do not agree, please do not use the App.",
      appUsage: "1. App Usage\nYou may use the App only for legal purposes and in accordance with these Terms. You must be at least 13 years old to use the App.",
      userAccounts: "2. User Accounts\nTo access certain features, you need to create an account or sign in with your Google account. You agree to provide accurate information and keep your account secure. You are responsible for all activity under your account.",
      userContent: "3. User-Generated Content\nUsers can record and manage their own golf rounds. You retain ownership of your data, but grant us a non-exclusive, worldwide, royalty-free license to use, host, and display your content for the purpose of operating and improving the App.",
      courseInfo: "4. Course Information\nThe App displays information about golf courses in Argentina collected from public sources or provided by users and club managers. While we strive to maintain accurate information, we do not guarantee its accuracy or completeness.",
      prohibitedConduct: "5. Prohibited Conduct\nYou agree not to:\n• Use the App for illegal purposes\n• Access protected parts without authorization\n• Interfere with the App's operation\n• Upload malicious software or viruses",
      intellectualProperty: "6. Intellectual Property\nAll App content (logos, texts, images, code) is owned by GolfitArgentina, unless otherwise indicated. Unauthorized use is prohibited.",
      modifications: "7. Modifications\nWe reserve the right to modify these Terms at any time. Continued use of the App constitutes your acceptance of the updated Terms.",
      termination: "8. Termination\nWe may suspend or terminate your access if you violate these Terms. Upon termination, your right to use the App immediately ceases.",
      contact: "9. Contact\nFor inquiries about these Terms, contact us at contacto@golfitargentina.com.",
      privacyTitle: "🔐 Privacy Policy",
      privacyEffectiveDate: "Effective Date: July 5th, 2025",
      privacyIntro: "At GolfitArgentina we are committed to protecting your privacy. This Privacy Policy describes how we collect, use, and protect your personal information.",
      infoCollection: "1. Information We Collect\n• Account data: Name, email address, Google account ID\n• Golf data: Information from the rounds you record\n• Technical data: IP address, browser type, device, and usage statistics",
      infoUsage: "2. Use of Information\nWe use your information to:\n• Operate and improve the App\n• Authenticate users via Google\n• Display and save your rounds\n• Respond to queries\n• Prevent misuse and ensure security",
      dataSharing: "3. Data Sharing\nWe do not sell your personal data. We may share information with:\n• Service providers (hosting, analytics)\n• Legal authorities, if required\n• In case of merger or acquisition",
      security: "4. Security and Storage\nYour data is stored securely. While we apply modern protection measures, no system is completely infallible.",
      userRights: "5. Your Rights\nYou have the right to:\n• Access your personal data\n• Correct or delete your information\n• Withdraw consent or request account deletion",
      cookies: "6. Cookies and Tracking Technologies\nWe may use cookies or analytics tools to improve the experience. You can disable them from your browser.",
      minorPrivacy: "7. Privacy of Minors\nThe App is not directed at minors under 13 years. We do not knowingly collect data from minors.",
      privacyContact: "8. Contact\nFor queries or requests, contact us at contacto@golfitargentina.com.",
      legalNoticeTitle: "⚖️ Legal Notice",
      ownerInfo: "Site and application owner: GolfitArgentina\nApp name: GolfitArgentina\nContact email: contacto@golfitargentina.com\nWebsite: www.golfitargentina.com\nLocation: San Isidro, Buenos Aires, Argentina",
      appPurpose: "App Purpose\nThe App aims to show users public information about golf courses in Argentina and allow them to record their own rounds. It is an independent and unofficial platform, with no direct link to golf associations unless expressly indicated.",
      disclaimer: "Disclaimer\nWhile we strive to provide updated and accurate information, GolfitArgentina is not responsible for errors, omissions, or damages arising from the use of the App.",
      intellectualPropertyNotice: "Intellectual Property\nAll intellectual property rights related to this App are owned by GolfitArgentina, unless otherwise indicated. Reproduction or redistribution without authorization is prohibited."
    },
    tournaments: {
      createTournament: "Create Tournament",
      tournamentDetails: "Tournament Details",
      tournamentName: "Tournament Name",
      tournamentNameRequired: "Tournament Name *",
      tournamentNamePlaceholder: "e.g., Friends Championship",
      description: "Description",
      descriptionPlaceholder: "Tournament description...",
      tournamentDate: "Tournament Date",
      tournamentDateRequired: "Tournament Date *",
      golfCourse: "Golf Course",
      golfCourseRequired: "Golf Course *",
      selectGolfCourse: "Select a golf course",
      loadingCourses: "Loading courses...",
      noCoursesAvailable: "No courses available",
      maxPlayers: "Max Players",
      format: "Format",
      strokePlay: "Stroke Play",
      matchPlay: "Match Play",
      selectParticipants: "Select Participants",
      noFriendsAvailable: "No friends available",
      addFriendsToInvite: "Add friends to invite them to tournaments",
      createTournamentButton: "Create Tournament",
      creatingTournament: "Creating Tournament...",
      fillRequiredFields: "Please fill in all required fields",
      startDateFuture: "Start date must be in the future",
      selectOneParticipant: "Please select at least one participant",
      tournamentCreatedSuccess: "Tournament created successfully!",
      failedToCreate: "Failed to create tournament"
    },
    matches: {
      challengeFriend: "Challenge Friend",
      matchDetails: "Match Details",
      matchName: "Match Name",
      matchNameRequired: "Match Name *",
      matchNamePlaceholder: "e.g., Sunday Showdown",
      matchDate: "Match Date",
      matchDateRequired: "Match Date *",
      golfCourse: "Golf Course",
      golfCourseRequired: "Golf Course *",
      selectGolfCourse: "Select a golf course",
      loadingCourses: "Loading courses...",
      noCoursesAvailable: "No courses available",
      matchFormat: "Match Format",
      matchFormatRequired: "Match Format *",
      strokePlay: "Stroke Play",
      matchPlay: "Match Play",
      stakes: "Stakes",
      stakesOptional: "Stakes (Optional)",
      stakesPlaceholder: "e.g., Loser buys dinner",
      chooseOpponent: "Choose Your Opponent",
      noFriendsAvailable: "No friends available",
      addFriendsToChallenge: "Add friends to challenge them to matches",
      matchPreview: "Match Preview",
      versus: "VS",
      you: "You",
      sendChallenge: "Send Challenge",
      sendingChallenge: "Sending Challenge...",
      fillRequiredFields: "Please fill in all required fields",
      matchDateFuture: "Match date must be in the future",
      matchChallengeSent: "Match challenge sent!",
      failedToCreate: "Failed to create match",
      matchChallenge: "Match Challenge!",
      youveBeenChallenged: "You've been challenged to a match",
      anonymousPlayer: "Anonymous Player", 
      challengedYou: "challenged you",
      decline: "Decline",
      declining: "Declining...",
      acceptChallenge: "Accept Challenge",
      accepting: "Accepting...",
      moreInvitations: "more invitation"
    },
    faq: {
      accountManagement: "Account Management",
      golfRounds: "Golf Rounds",
      courseInfo: "Course Information",
      technicalSupport: "Technical Support",
      q1: "How do I create an account?",
      a1: "You can create an account using your email or by signing in with Google from the home page.",
      q2: "How do I record a new golf round?",
      a2: "Use the 'Add Round' button in your profile, select the course, enter your score and date of play.",
      q3: "Can I view my previous rounds?",
      a3: "Yes, all your previous rounds are available in the Profile section, organized by date.",
      q4: "How do I update course information?",
      a4: "If you find incorrect information, you can contact us at contacto@golfitargentina.com to request an update.",
      q5: "Does the app work without internet connection?",
      a5: "Some basic functions are available offline, but you need internet to sync your data and see updated information.",
      q6: "How do I change my language settings?",
      a6: "You can change the language in the Settings section, where you'll find options for Spanish and English.",
      q7: "How do I contact technical support?",
      a7: "For technical help, contact us at contacto@golfitargentina.com. Our support hours are Monday-Friday, 9am-5pm."
    },
    notifications: {
      noNotifications: "No notifications",
      allCaughtUp: "You're all caught up!",
      from: "From",
      friendRequestTitle: "Friend Request",
      friendRequestMessage: "sent you a friend request",
      matchChallengeTitle: "Match Challenge",
      matchChallengeMessage: "challenged you to a match",
      matchAcceptedTitle: "Match Accepted",
      matchAcceptedMessage: "accepted your match challenge",
      matchDeclinedTitle: "Match Declined",
      matchDeclinedMessage: "declined your match challenge",
      unknownUser: "Unknown User"
    },
    friends: {
      noFriends: "No Friends",
      noRequests: "No Requests",
      findFriends: "Find friends to connect with",
      startConnecting: "Find and connect with friends!",
      removeFriend: "Remove Friend?",
      removeFriendDesc: "This will remove the user from your friends list.",
      receivedRequests: "Received Requests",
      sentRequests: "Sent Requests",
      pending: "Pending"
    }
  },
  es: {
    common: {
      search: "Buscar",
      filter: "Filtrar",
      home: "Inicio",
      profile: "Perfil",
      settings: "Ajustes",
      cancel: "Cancelar",
      submit: "Enviar",
      create: "Crear",
      edit: "Editar",
      delete: "Eliminar",
      save: "Guardar",
      back: "Atrás",
      next: "Siguiente",
      continue: "Continuar",
      done: "Hecho",
      welcome: "Bienvenido",
      loading: "Cargando...",
      players: "Jugadores",
      error: "Error",
      notifications: "Notificaciones"
    },
    auth: {
      signIn: "Iniciar Sesión",
      signUp: "Registrarse",
      email: "Correo electrónico",
      password: "Contraseña",
      forgotPassword: "¿Olvidaste tu contraseña?",
      alreadyHaveAccount: "¿Ya tienes una cuenta?",
      dontHaveAccount: "¿No tienes una cuenta?",
      haveAccount: "¿Ya tienes cuenta? Iniciar Sesión",
      createAccount: "Crear Cuenta",
      or: "O",
      continueWithGoogle: "Continuar con Google",
      continueWithApple: "Continuar con Apple",
      orContinueWith: "O continuar con",
      welcomeBack: "Bienvenido de Vuelta",
      emailSignInDescription: "Ingresa tu correo para iniciar sesión",
      emailSignUpDescription: "Ingresa tu correo para crear tu cuenta",
      checkEmail: "Revisa tu correo",
      confirmationEmailSent: "Se ha enviado un correo de confirmación"
    },
    home: {
      featuredCourses: "Campos Destacados",
      exploreAll: "Explorar Todo",
      nearbyGolfCourses: "Campos de Golf Cercanos",
      viewAll: "Ver Todo",
      upcomingReservations: "Reservas Próximas",
      noReservations: "Aún no tienes reservaciones.",
      searchCourses: "Buscar Campos",
      golfCourses: "Campos de Golf",
      noCoursesFound: "No se encontraron campos",
      resetFilters: "Restablecer Filtros",
      openNow: "Abierto",
      closed: "Cerrado",
      openInMap: "Ver en Mapa",
      location: "Ubicación",
      hours: "Horario",
      today: "Hoy de"
    },
    course: {
      holes: "Hoyos",
      par: "Par",
      openNow: "Abierto Ahora",
      closed: "Cerrado",
      hours: "Horario",
      address: "Dirección",
      contact: "Contacto",
      website: "Sitio Web",
      directions: "Cómo Llegar",
      description: "Descripción",
      reviews: "Reseñas",
      photos: "Fotos",
      openingHours: "Horarios de Apertura",
      hoursNotAvailable: "Horarios no disponibles",
      today: "Hoy",
      hide: "Ocultar",
      viewAll: "Ver Todos",
      courseStatistics: "Estadísticas del Campo",
      noRoundsPlayed: "Aún no se han jugado rondas",
      totalHoles: "Total de Hoyos",
      totalPar: "Par Total",
      frontNine: "Primeros Nueve",
      backNine: "Últimos Nueve",
      courseTotals: "Totales del Campo",
      weatherForecast: "Pronóstico del Tiempo",
      loadingWeather: "Cargando clima...",
      tryAgain: "Intentar de Nuevo",
      dayForecast: "Pronóstico de 5 Días",
      humidity: "Humedad",
      wind: "Viento",
      courseLocation: "Ubicación del Campo",
      noRoundsRecorded: "Sin Rondas Registradas",
      firstToPlayCourse: "¡Sé el primero en jugar este campo y registrar tu puntuación para ver estadísticas y tablas de posiciones!",
      totalRounds: "Rondas Totales",
      averageVsPar: "Promedio vs Par",
      bestRound: "Mejor Ronda",
      players: "Jugadores",
      highestRound: "Ronda Más Alta",
      monday: "Lunes",
      tuesday: "Martes",
      wednesday: "Miércoles", 
      thursday: "Jueves",
      friday: "Viernes",
      saturday: "Sábado",
      sunday: "Domingo",
      noReviewsYet: "Aún no hay reseñas",
      firstToAddReview: "¡Sé el primero en agregar una reseña!",
      sunny: "Soleado",
      partlyCloudy: "Parcialmente Nublado",
      cloudy: "Nublado",
      overcast: "Encapotado",
      rain: "Lluvia",
      thunderstorm: "Tormenta",
      snow: "Nieve",
      fog: "Niebla",
      haze: "Bruma",
      drizzle: "Llovizna",
      mist: "Neblina",
      fiveDayForecast: "Pronóstico de 5 Días"
    },
    profile: {
      yourProfile: "Tu Perfil",
      handicap: "Hándicap",
      viewStats: "Ver Estadísticas",
      roundsPlayed: "Rondas Jugadas",
      avgScore: "Puntuación Media",
      bestScore: "Mejor Puntuación",
      yourRecentRounds: "Tus Rondas Recientes",
      noRounds: "Aún no has registrado ninguna ronda.",
      addRound: "Añadir Ronda",
      account: "Cuenta",
      holes: "Hoyos",
      noRoundsRecorded: "Aún no hay rondas registradas",
      addFirstRound: "Añadir tu primera ronda",
      noStatsAvailable: "Aún no hay estadísticas disponibles",
      startPlayingStats: "¡Empieza a jugar para ver tus estadísticas!",
      noHandicapYet: "Aún sin hándicap",
      playerStatistics: "Estadísticas del Jugador",
      recentRounds: "Rondas Recientes",
      recordFirstRound: "Registra tu primera ronda",
      allRounds: "Todas las Rondas",
      viewAllRounds: "Ver Todas las Rondas",
      viewAll: "Ver todas",
      showLess: "Mostrar Menos",
      deleteRound: "Eliminar Ronda",
      deleteRoundConfirm: "¿Estás seguro de que quieres eliminar esta ronda? Esta acción no se puede deshacer.",
      score: "Puntuación",
      notes: "Notas",
      underPar: "bajo par",
      overPar: "sobre par", 
      atPar: "En par",
      logout: "Cerrar Sesión",
      logoutConfirm: "¿Estás seguro de que quieres cerrar sesión?",
      logoutSuccess: "Sesión cerrada exitosamente",
      logoutError: "Error al cerrar sesión",
      totalRounds: "Rondas Totales",
      avgVsPar: "Prom. vs Par",
      bestRound: "Mejor Ronda",
      viewScorecard: "Ver Scorecard",
      saveChanges: "Guardar Cambios",
      profileUpdateSuccess: "Perfil actualizado exitosamente",
      profileUpdateError: "Error al actualizar el perfil",
      fullName: "Nombre Completo",
      username: "Nombre de Usuario",
      anonymous: "Anónimo",
      saving: "Guardando..."
    },
    filters: {
      showFavorites: "Mostrar Canchas Favoritas",
      numberOfHoles: "Cantidad de Hoyos",
      status: "Estado",
      favoritesOnly: "Solo Favoritas",
      currentlyOpen: "Actualmente Abierto",
      all: "Todas",
      topRated: "Mejor Valoradas",
      showOnlyFavorites: "Mostrar solo tus canchas favoritas",
      showAllCourses: "Mostrar todas las canchas incluyendo favoritas",
      showOnlyOpen: "Mostrar solo canchas abiertas",
      showAllStatus: "Mostrar todas las canchas sin importar el estado",
      findYourCourse: "Busca tu cancha indicada"
    },
    addRound: {
      title: "Agrega tu ronda",
      selectCourse: "Seleccionar Campo de Golf",
      chooseCourse: "Elige el campo de golf donde jugaste tu ronda",
      searchCourse: "Buscar y seleccionar campo de golf...",
      roundDetails: "Detalles de la Ronda",
      howManyHoles: "¿Cuántos hoyos jugaste?",
      selected: "Seleccionado",
      enterScores: "Ingresa Tus Puntuaciones",
      addScoreHole: "Agrega tu puntuación para cada hoyo",
      addScores: "Agregar Puntuaciones",
      saveRound: "Guardar Ronda",
      saving: "Guardando...",
      saveSuccess: "¡Ronda guardada exitosamente!",
      selectCourseError: "Por favor selecciona un campo",
      loginError: "Por favor inicia sesión para agregar una ronda",
      selectGolfCourse: "Seleccionar Campo de Golf",
      chooseCoursePlay: "Elige el campo donde quieres jugar",
      searchGolfCourses: "Buscar campos de golf...",
      noGolfCourseFound: "No se encontró ningún campo de golf.",
      holesPlayed: "Hoyos Jugados",
      holes: "Hoyos",
      select9Holes: "Seleccionar 9 Hoyos",
      choose9Holes: "Elige qué 9 hoyos jugaste",
      front9: "Primeros 9",
      back9: "Últimos 9",
      holes1to9: "Hoyos 1-9",
      holes10to18: "Hoyos 10-18",
      step: "Paso",
      of: "de"
    },
    rounds: {
      addRound: "Añadir Ronda",
      selectCourse: "Seleccionar Campo",
      date: "Fecha",
      score: "Puntuación",
      notes: "Notas",
      searchCourses: "Buscar campos...",
      noCoursesFound: "No se encontraron campos",
      courseSearchPlaceholder: "Escribe para buscar un campo...",
      roundAdded: "Ronda añadida con éxito",
      roundAddedDesc: "Tu ronda de golf ha sido guardada.",
      courseRequired: "Por favor selecciona un campo",
      scoreRequired: "Por favor ingresa tu puntuación",
      dateRequired: "Por favor selecciona una fecha",
      hole: "Hoyo",
      par: "Par",
      strokes: "Golpes",
      addShots: "Añadir Tiros",
    },
    reservations: {
      bookTeeTime: "Reservar Horario",
      date: "Fecha",
      time: "Hora",
      players: "Jugadores",
      bookingDetails: "Detalles de la Reserva",
      confirmBooking: "Confirmar Reserva",
      bookingConfirmed: "Reserva Confirmada",
      bookingFailed: "Error en la Reserva",
      upcoming: "Próximas",
      past: "Pasadas",
      cancelReservation: "Cancelar Reserva",
      myReservations: "Mis Reservas",
      noReservations: "No se encontraron reservas"
    },
    settings: {
      settings: "Ajustes",
      legalNotice: "Aviso Legal",
      faq: "Preguntas Frecuentes",
      language: "Idioma",
      darkMode: "Modo Oscuro",
      privacyPolicy: "Política de Privacidad",
      termsConditions: "Términos y Condiciones"
    },
    legal: {
      effectiveDate: "Fecha de entrada en vigor: 5 de Julio del 2025",
      welcomeText: "Bienvenido a GolfitArgentina, una aplicación web progresiva que brinda información detallada sobre todas las canchas de golf en Argentina. Al acceder o utilizar nuestra App, aceptás quedar legalmente vinculado por estos Términos y Condiciones. Si no estás de acuerdo, por favor no utilices la App.",
      appUsage: "1. Uso de la App\nPodés utilizar la App únicamente para fines legales y de acuerdo con estos Términos. Debés tener al menos 13 años para usar la App.",
      userAccounts: "2. Cuentas de Usuario\nPara acceder a ciertas funciones, se requiere crear una cuenta o iniciar sesión con tu cuenta de Google. Aceptás proporcionar información precisa y mantener segura tu cuenta. Sos responsable de toda actividad realizada bajo tu cuenta.",
      userContent: "3. Contenido Generado por el Usuario\nLos usuarios pueden registrar y administrar sus propias rondas de golf. Conservás la propiedad de tus datos, pero nos otorgás una licencia no exclusiva, mundial y libre de regalías para usar, alojar y mostrar tu contenido con el fin de operar y mejorar la App.",
      courseInfo: "4. Información de Canchas\nLa App muestra información sobre canchas de golf en Argentina recopilada de fuentes públicas o proporcionada por usuarios y responsables de los clubes. Aunque buscamos mantener la información precisa, no garantizamos su exactitud o integridad.",
      prohibitedConduct: "5. Conductas Prohibidas\nAceptás no:\n• Utilizar la App para fines ilegales\n• Acceder sin autorización a partes protegidas\n• Interferir con el funcionamiento de la App\n• Subir software malicioso o virus",
      intellectualProperty: "6. Propiedad Intelectual\nTodo el contenido de la App (logotipos, textos, imágenes, código) es propiedad de GolfitArgentina, salvo que se indique lo contrario. Su uso no autorizado está prohibido.",
      modifications: "7. Modificaciones\nNos reservamos el derecho de modificar estos Términos en cualquier momento. El uso continuado de la App constituye tu aceptación de los Términos actualizados.",
      termination: "8. Terminación\nPodemos suspender o terminar tu acceso si violás estos Términos. En caso de terminación, cesa inmediatamente tu derecho a utilizar la App.",
      contact: "9. Contacto\nPara consultas sobre estos Términos, escribinos a contacto@golfitargentina.com.",
      privacyTitle: "🔐 Política de Privacidad",
      privacyEffectiveDate: "Fecha de entrada en vigor: 5 de Julio del 2025",
      privacyIntro: "En GolfitArgentina nos comprometemos a proteger tu privacidad. Esta Política de Privacidad describe cómo recopilamos, usamos y protegemos tu información personal.",
      infoCollection: "1. Información que Recopilamos\n• Datos de cuenta: Nombre, dirección de correo electrónico, ID de cuenta de Google\n• Datos de golf: Información de las rondas que registrás\n• Datos técnicos: Dirección IP, tipo de navegador, dispositivo y estadísticas de uso",
      infoUsage: "2. Uso de la Información\nUtilizamos tu información para:\n• Operar y mejorar la App\n• Autenticar a los usuarios vía Google\n• Mostrar y guardar tus rondas\n• Responder consultas\n• Prevenir usos indebidos y garantizar la seguridad",
      dataSharing: "3. Compartición de Datos\nNo vendemos tus datos personales. Podemos compartir información con:\n• Proveedores de servicios (hosting, analítica)\n• Autoridades legales, si es requerido\n• En caso de fusión o adquisición",
      security: "4. Seguridad y Almacenamiento\nTus datos son almacenados de forma segura. Aunque aplicamos medidas modernas de protección, ningún sistema es completamente infalible.",
      userRights: "5. Tus Derechos\nTenés derecho a:\n• Acceder a tus datos personales\n• Corregir o eliminar tu información\n• Retirar tu consentimiento o solicitar la eliminación de tu cuenta",
      cookies: "6. Cookies y Tecnologías de Seguimiento\nPodemos usar cookies o herramientas de analítica para mejorar la experiencia. Podés desactivarlas desde tu navegador.",
      minorPrivacy: "7. Privacidad de Menores\nLa App no está dirigida a menores de 13 años. No recopilamos datos conscientemente de menores.",
      privacyContact: "8. Contacto\nPara consultas o solicitudes, escribinos a contacto@golfitargentina.com.",
      legalNoticeTitle: "⚖️ Aviso Legal",
      ownerInfo: "Titular del sitio y aplicación: GolfitArgentina\nNombre de la App: GolfitArgentina\nCorreo electrónico de contacto: contacto@golfitargentina.com\nSitio web: www.golfitargentina.com\nUbicación: San Isidro, Buenos Aires, Argentina",
      appPurpose: "Finalidad de la App\nLa App tiene como finalidad mostrar a los usuarios información pública sobre canchas de golf en Argentina y permitirles registrar sus propias rondas. Es una plataforma independiente y no oficial, sin vínculo directo con asociaciones de golf salvo que se indique expresamente.",
      disclaimer: "Exención de Responsabilidad\nSi bien se procura que la información brindada sea actualizada y precisa, GolfitArgentina no se responsabiliza por errores, omisiones o daños derivados del uso de la App.",
      intellectualPropertyNotice: "Propiedad Intelectual\nTodos los derechos de propiedad intelectual relacionados con esta App son titularidad de GolfitArgentina, salvo que se indique lo contrario. Queda prohibida la reproducción o redistribución sin autorización."
    },
    tournaments: {
      createTournament: "Crear Torneo",
      tournamentDetails: "Detalles del Torneo",
      tournamentName: "Nombre del Torneo",
      tournamentNameRequired: "Nombre del Torneo *",
      tournamentNamePlaceholder: "ej., Campeonato de Amigos",
      description: "Descripción",
      descriptionPlaceholder: "Descripción del torneo...",
      tournamentDate: "Fecha del Torneo",
      tournamentDateRequired: "Fecha del Torneo *",
      golfCourse: "Campo de Golf",
      golfCourseRequired: "Campo de Golf *",
      selectGolfCourse: "Seleccionar un campo de golf",
      loadingCourses: "Cargando campos...",
      noCoursesAvailable: "No hay campos disponibles",
      maxPlayers: "Máximo de Jugadores",
      format: "Formato",
      strokePlay: "Stroke Play",
      matchPlay: "Match Play",
      selectParticipants: "Seleccionar Participantes",
      noFriendsAvailable: "No hay amigos disponibles",
      addFriendsToInvite: "Añade amigos para invitarlos a torneos",
      createTournamentButton: "Crear Torneo",
      creatingTournament: "Creando Torneo...",
      fillRequiredFields: "Por favor completa todos los campos obligatorios",
      startDateFuture: "La fecha de inicio debe ser en el futuro",
      selectOneParticipant: "Por favor selecciona al menos un participante",
      tournamentCreatedSuccess: "¡Torneo creado exitosamente!",
      failedToCreate: "Error al crear el torneo"
    },
    matches: {
      challengeFriend: "Desafiar Amigo",
      matchDetails: "Detalles del Partido",
      matchName: "Nombre del Partido",
      matchNameRequired: "Nombre del Partido *",
      matchNamePlaceholder: "ej., Duelo Dominical",
      matchDate: "Fecha del Partido",
      matchDateRequired: "Fecha del Partido *",
      golfCourse: "Campo de Golf",
      golfCourseRequired: "Campo de Golf *",
      selectGolfCourse: "Seleccionar un campo de golf",
      loadingCourses: "Cargando campos...",
      noCoursesAvailable: "No hay campos disponibles",
      matchFormat: "Formato del Partido",
      matchFormatRequired: "Formato del Partido *",
      strokePlay: "Stroke Play",
      matchPlay: "Match Play",
      stakes: "Apuesta",
      stakesOptional: "Apuesta (Opcional)",
      stakesPlaceholder: "ej., El perdedor paga la cena",
      chooseOpponent: "Elige tu Oponente",
      noFriendsAvailable: "No hay amigos disponibles",
      addFriendsToChallenge: "Añade amigos para desafiarlos a partidos",
      matchPreview: "Vista Previa del Partido",
      versus: "VS",
      you: "Tú",
      sendChallenge: "Enviar Desafío",
      sendingChallenge: "Enviando Desafío...",
      fillRequiredFields: "Por favor completa todos los campos obligatorios",
      matchDateFuture: "La fecha del partido debe ser en el futuro",
      matchChallengeSent: "¡Desafío enviado!",
      failedToCreate: "Error al crear el partido",
      matchChallenge: "¡Desafío de Match!",
      youveBeenChallenged: "Te han desafiado a un partido",
      anonymousPlayer: "Jugador Anónimo",
      challengedYou: "te ha desafiado",
      decline: "Rechazar", 
      declining: "Rechazando...",
      acceptChallenge: "Aceptar Desafío",
      accepting: "Aceptando...",
      moreInvitations: "invitación más"
    },
    faq: {
      accountManagement: "Gestión de Cuenta",
      golfRounds: "Rondas de Golf",
      courseInfo: "Información de Canchas",
      technicalSupport: "Soporte Técnico",
      q1: "¿Cómo creo una cuenta?",
      a1: "Podés crear una cuenta usando tu correo electrónico o iniciando sesión con Google desde la página de inicio.",
      q2: "¿Cómo registro una nueva ronda de golf?",
      a2: "Usa el botón 'Añadir Ronda' en tu perfil, selecciona la cancha, ingresa tu puntuación y fecha de juego.",
      q3: "¿Puedo ver mis rondas anteriores?",
      a3: "Sí, todas tus rondas anteriores están disponibles en la sección de Perfil, organizadas por fecha.",
      q4: "¿Cómo actualizo la información de una cancha?",
      a4: "Si encontrás información incorrecta, podés contactarnos a contacto@golfitargentina.com para solicitar una actualización.",
      q5: "¿La aplicación funciona sin conexión a internet?",
      a5: "Algunas funciones básicas están disponibles sin conexión, pero necesitás internet para sincronizar tus datos y ver información actualizada.",
      q6: "¿Cómo cambio mi configuración de idioma?",
      a6: "Podés cambiar el idioma en la sección Ajustes, donde encontrarás opciones para Español e Inglés.",
      q7: "¿Cómo contacto al soporte técnico?",
      a7: "Para ayuda técnica, escribinos a contacto@golfitargentina.com. Nuestro horario de atención es de Lunes a Viernes, 9am-5pm."
    },
    notifications: {
      noNotifications: "Sin notificaciones",
      allCaughtUp: "¡Estás al día!",
      from: "De",
      friendRequestTitle: "Solicitud de Amistad",
      friendRequestMessage: "te envió una solicitud de amistad",
      matchChallengeTitle: "Desafío de Match",
      matchChallengeMessage: "te desafió a un partido",
      matchAcceptedTitle: "Match Aceptado",
      matchAcceptedMessage: "aceptó tu desafío de match",
      matchDeclinedTitle: "Match Rechazado",
      matchDeclinedMessage: "rechazó tu desafío de match",
      unknownUser: "Usuario Desconocido"
    },
    friends: {
      noFriends: "Sin Amigos",
      noRequests: "Sin solicitudes",
      findFriends: "Busca amigos para conectar",
      startConnecting: "¡Busca y conecta con amigos!",
      removeFriend: "¿Eliminar amigo?",
      removeFriendDesc: "Esto eliminará al usuario de tu lista de amigos.",
      receivedRequests: "Solicitudes recibidas",
      sentRequests: "Solicitudes enviadas",
      pending: "Pendiente"
    }
  }
};

// Create context for language
interface LanguageContextType {
  language: LanguageType;
  setLanguage: (lang: LanguageType) => void;
  t: (section: string, key: string) => string;
}

const LanguageContext = createContext<LanguageContextType>({
  language: "en",
  setLanguage: () => {},
  t: () => "",
});

// Hook for accessing the language context
export const useLanguage = () => useContext(LanguageContext);

// Language provider component
interface LanguageProviderProps {
  children: ReactNode;
}

export const LanguageProvider: React.FC<LanguageProviderProps> = ({ children }) => {
  const [language, setLanguage] = useState<LanguageType>(() => {
    const savedLanguage = localStorage.getItem("language");
    return (savedLanguage as LanguageType) || "es";
  });

  // Save language preference to localStorage when it changes
  const handleSetLanguage = (lang: LanguageType) => {
    setLanguage(lang);
    localStorage.setItem("language", lang);
  };

  // Translation function
  const t = (section: string, key: string): string => {
    try {
      return translations[language][section][key] || key;
    } catch (error) {
      console.warn(`Translation missing: ${section}.${key}`);
      return key;
    }
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage: handleSetLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export default LanguageContext;
