// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zlmotrppstqjnovpfgbd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InpsbW90cnBwc3Rxam5vdnBmZ2JkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDA2MTcwOTYsImV4cCI6MjA1NjE5MzA5Nn0.1TwfkCE7nChIbPQIXZEjjLFoHFbProrDJ8UXrnvdMac";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);